- name: Generate stats
  run: python generate_readme.py

- name: Commit changes
  run: |
    git config user.name "github-actions"
    git config user.email "github-actions@github.com"
    git add README.md

    git commit -m "update stats" || exit 0

- name: Push changes
  run: git push
